version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq/
#        - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
#        - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
        - rabbitmq_go_net
  simulationdb:
    build: ./SimulationDb
    # command: postgres
    ports:
      - "5432:5432"
    environment: # TODO Remove secrets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SimulationDb
networks: 
  rabbitmq_go_net:
    driver: bridge