version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./RabbitMQ/data/:/var/lib/rabbitmq/
      - ./RabbitMQ/log/:/var/log/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - rabbitmq_net
  simulationdb:
    build: ./SimulationDb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment: # TODO Remove secrets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SimulationDb
      - MAP_FILE=krakow.osm
      - DISTRICTS_FILE=krakow-districts.osm
    volumes:
      - ./SimulationDb/maps:/maps
    networks:
      - simulation_net
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./Loki/Data:/tmp/loki
      - ./Loki/loki-config.yaml:/mnt/config/loki-config.yaml
    networks:
      - loki_net
    # command: -config.file=/mnt/config/loki-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: wget -q --tries=1 -O- http://localhost:3100/ready
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s
  grafana:
    image: grafana/grafana:latest
    depends_on:
      loki:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./Grafana/Data:/var/lib/grafana
      - ./Grafana/Provisioning/:/etc/grafana/provisioning/
    networks:
      - loki_net
networks:
  rabbitmq_net:
    driver: bridge
  loki_net:
    driver: bridge
  simulation_net:
    driver: bridge
