version: "3.8"
services:
  # Base
  rabbitmq:
    extends:
      file: infrastructure-docker-compose.yaml
      service: rabbitmq
  simulationdb:
    extends:
      file: infrastructure-docker-compose.yaml
      service: simulationdb
  loki:
    extends:
      file: infrastructure-docker-compose.yaml
      service: loki
  grafana:
    extends:
      file: infrastructure-docker-compose.yaml
      service: grafana
  simulation:
    extends:
      file: police-services-docker-compose.yaml
      service: simulation
  hqservice:
    extends:
      file: police-services-docker-compose.yaml
      service: hqservice
  webapp:
    extends:
      file: police-services-docker-compose.yaml
      service: webapp
  #Patrols
  patrol_0:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=0
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=fdadd28d-4768-417e-a041-8fd66a25961d
      - PoliceSupportSystem_PatrolSettings__NavAgentId=9c38efa2-4153-46fe-9ce1-2dd3b7dddd25
      - PoliceSupportSystem_PatrolSettings__GunAgentId=552db772-bd29-4fb0-b469-084b308859ec
  patrol_1:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=1
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=024ac982-55bd-40f1-a0b5-2aaffacc9b6b
      - PoliceSupportSystem_PatrolSettings__NavAgentId=57b3297b-fcb9-4652-9e80-e16f28eb7b19
      - PoliceSupportSystem_PatrolSettings__GunAgentId=9943fbd6-ab71-4369-979f-c88f4f7625b8
  patrol_2:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=2
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=832d872a-69ea-4cbb-843f-25b0f9531c63
      - PoliceSupportSystem_PatrolSettings__NavAgentId=828b011e-662e-4629-84fb-ca0bd7211a80
      - PoliceSupportSystem_PatrolSettings__GunAgentId=6fcefc34-8b2b-4746-b7c9-4dfe3e9f32c8
  patrol_3:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=3
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=fc9d538c-9500-44c4-a659-66c9105c7d0a
      - PoliceSupportSystem_PatrolSettings__NavAgentId=3b4b8a85-e853-432a-a346-061d67e0c76b
      - PoliceSupportSystem_PatrolSettings__GunAgentId=aa3d3d69-94f4-4c43-9371-cf320ffa5108
  patrol_4:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=4
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=ff0cb69d-ab5f-46a5-bf65-d31a3e4277c8
      - PoliceSupportSystem_PatrolSettings__NavAgentId=44ba07de-5780-46ab-b92c-a3bf0e84630d
      - PoliceSupportSystem_PatrolSettings__GunAgentId=46f7a1bf-49bd-4987-916b-104d32a00f7e
  patrol_5:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=5
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=9f61aac5-be3c-4fbd-8539-d7a8178eb80b
      - PoliceSupportSystem_PatrolSettings__NavAgentId=ffbe80a4-7d2d-4b60-8c31-ffc970e0f8c1
      - PoliceSupportSystem_PatrolSettings__GunAgentId=e678215f-52ba-4754-8472-79a5cf40807b
  patrol_6:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=6
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=0f2e9cca-5cda-4c04-b244-fa8ba698aca3
      - PoliceSupportSystem_PatrolSettings__NavAgentId=ac65de5e-550a-47dd-8234-516d9d9f806c
      - PoliceSupportSystem_PatrolSettings__GunAgentId=72eace22-bf2a-42d1-88cb-92a7a2e9abc2
  patrol_7:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=7
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=bdefb4c0-b92b-428a-9092-b45e7655fda6
      - PoliceSupportSystem_PatrolSettings__NavAgentId=5ee46382-047f-4110-9772-4da5450814dc
      - PoliceSupportSystem_PatrolSettings__GunAgentId=59a3fc0f-38b4-410d-912b-0c8b4f6852c8
  patrol_8:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=8
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=4e21d974-af91-4951-b844-209448cb24d5
      - PoliceSupportSystem_PatrolSettings__NavAgentId=cfe6f75a-a559-4fa2-8f6e-b00c433a49fb
      - PoliceSupportSystem_PatrolSettings__GunAgentId=db78038f-bd84-49a7-8e9c-ac90e7d3fe5c
  patrol_9:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=9
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=23a0db9e-dc82-45f4-995e-cd9cdf73e10f
      - PoliceSupportSystem_PatrolSettings__NavAgentId=763068d2-e291-4bf2-961d-b39ce776851e
      - PoliceSupportSystem_PatrolSettings__GunAgentId=56ce4f4d-74c1-4378-a866-0be9c0a5cd85
  patrol_10:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=10
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=d630936f-eac1-49af-912b-bdb77c2c2b7f
      - PoliceSupportSystem_PatrolSettings__NavAgentId=0859b6c0-51d8-41d6-9a91-b8809be757af
      - PoliceSupportSystem_PatrolSettings__GunAgentId=c924e981-f610-43de-b1f7-9b8cdbf09b95
  patrol_11:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=11
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=ac8dd6eb-5f17-4c49-ac92-ea53186bc106
      - PoliceSupportSystem_PatrolSettings__NavAgentId=5cda35e0-1375-4c93-9986-585ea978fcf7
      - PoliceSupportSystem_PatrolSettings__GunAgentId=4c371a66-804a-4b6e-b940-7c6c0c493bad
  patrol_12:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=12
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=85a23c18-0650-431f-8995-1ca12fc70935
      - PoliceSupportSystem_PatrolSettings__NavAgentId=7da52437-a7fd-4a4f-841d-93811ca6cc8e
      - PoliceSupportSystem_PatrolSettings__GunAgentId=8675c034-b20f-4067-8abd-a068527562f5
  patrol_13:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=13
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=c7939a4e-b2d2-4773-a4cf-a034dd9262c0
      - PoliceSupportSystem_PatrolSettings__NavAgentId=c75dab3e-bb3f-4a27-8b64-b6326d0106ca
      - PoliceSupportSystem_PatrolSettings__GunAgentId=04bf8b98-91d7-4790-8893-e8769a95e65f
  patrol_14:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=14
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=047c1364-0329-4f81-a898-3273e87e1929
      - PoliceSupportSystem_PatrolSettings__NavAgentId=dd9bb56a-30bb-4982-9309-e5b00d8d78f6
      - PoliceSupportSystem_PatrolSettings__GunAgentId=0cc2bfb1-a516-47d6-a58c-9f8e0915a631
  patrol_15:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=15
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=3f01958d-b510-459e-a0f5-0d65bfc79463
      - PoliceSupportSystem_PatrolSettings__NavAgentId=9faacae1-eba0-40fe-8029-c7ab2ae0211b
      - PoliceSupportSystem_PatrolSettings__GunAgentId=78e92305-ebc0-40eb-b3b3-beffe63988fe
  patrol_16:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=16
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=22df32d7-0675-4f57-887d-1e748fcfed06
      - PoliceSupportSystem_PatrolSettings__NavAgentId=b9f5610a-7be4-4e1a-8828-03dab1659370
      - PoliceSupportSystem_PatrolSettings__GunAgentId=22d91035-dff9-4f25-a9c3-73130afbb7cb
  patrol_17:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=17
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=c8ee6ce9-d4cb-47af-b08a-d762de0bf7e3
      - PoliceSupportSystem_PatrolSettings__NavAgentId=f7e86064-4452-4934-84e6-d89065e880f7
      - PoliceSupportSystem_PatrolSettings__GunAgentId=e89435f7-549f-437b-92a1-1bb59b5dd15f
  patrol_18:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=18
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=ef7de742-4de2-4f7b-a762-b3a1377ddd4f
      - PoliceSupportSystem_PatrolSettings__NavAgentId=80b86c4d-1170-4bfc-b0ec-037d9712fa38
      - PoliceSupportSystem_PatrolSettings__GunAgentId=a500eb47-3c66-49c1-a0f4-aa3bb129bbdd
  patrol_19:
    extends:
      file: patrol-docker-compose.yaml
      service: patrol
    environment:
      - PoliceSupportSystem_PatrolSettings__PatrolId=19
      - PoliceSupportSystem_PatrolSettings__PatrolAgentId=1bbe919f-1a0e-440a-a559-cf56faff73cc
      - PoliceSupportSystem_PatrolSettings__NavAgentId=e5326750-0dc1-4a67-a0e1-6701872e55e7
      - PoliceSupportSystem_PatrolSettings__GunAgentId=a89a05f8-ad9c-4fd8-83b8-7bb235cc9003
networks:
  rabbitmq_net:
    driver: bridge
  loki_net:
    driver: bridge
  simulation_net:
    driver: bridge
