version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./RabbitMQ/data/:/var/lib/rabbitmq/
        - ./RabbitMQ/log/:/var/log/rabbitmq/
    networks:
        - rabbitmq_go_net
  simulationdb:
    build: ./SimulationDb
    ports:
      - "5432:5432"
    environment: # TODO Remove secrets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SimulationDb
      - MAP_FILE=krakow.osm
    volumes:
      - ./SimulationDb/maps:/maps
networks: 
  rabbitmq_go_net:
    driver: bridge